spring.application.name=shankarbank
spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${Local_DB_URL}
spring.datasource.username=${Local_DB_USERNAME}
spring.datasource.password=${Local_DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

server.port=${PORT}

